#!/usr/bin/env python
# -*- coding: utf-8 -*-

## Tango-RedPitaya -- Tango device server for RedPitaya multi-istrument board
## Solaris <synchrotron.pl>
## Copyright (C) 2015 Grzegorz Kowalski <daneos@daneos.com>
## See LICENSE for legal information


from PyTango import AttrQuality, AttrWriteType, DevState
from PyTango.server import run
from PyTango.server import Device, DeviceMeta
from PyTango.server import attribute, command, device_property

from PyRedPitaya.pc import RedPitaya
from rpyc import connect
from rpyc.core.protocol import PingError	# btw. this doesn't work


class RedPitayaBoard(Device):
	""" RedPitaya device server class """
	__metaclass__ = DeviceMeta


	### RPyC connection details -----------------------------------------------

	host = device_property(dtype=str)							# board hostname
	port = device_property(dtype=int, default_value=18861)		# board port
	reconnect = device_property(dtype=int, default_value=10)	# max reconnect attepts


	### Utilities -------------------------------------------------------------

	def connection_error(self, e):
		""" Set status message informing about connection error and appropiate state """
		self.set_state(DevState.FAULT)
		self.status_message = "Could not connect to the board @ %s:%d\nError message: %s\n" % (self.host, self.port, str(e))
		self.status_message += "Reconnect attempt %d / %d\n" % (self.reconnect_tries, self.reconnect)
		if self.reconnect_tries == self.reconnect:
			self.status_message += "Not trying again."

	def board_connect(self):
		""" Connect to the board """
		try:
			self.conn = connect(self.host, self.port)
			self.RP = RedPitaya(self.conn)
		except Exception as e:
			self.connection_error(e)
		else:
			self.set_state(DevState.ON)
			self.status_message = ""


	### Interface methods -----------------------------------------------------

	def init_device(self):
		""" Start device server """
		Device.init_device(self)

		self.reconnect_tries = 0

		self.set_state(DevState.INIT)
		self.board_connect()	# connect to the board
		

	def dev_status(self):
		""" Display appropiate status message """
		#if not hasattr(self, "status_message"): self.status_message = ""
		self._status = "Device is in %s state.\n%s" % (self.get_state(), self.status_message)
		self.set_status(self._status)
		return self._status


	### Attributes ------------------------------------------------------------

	@attribute(label="FPGA Temperature", dtype=float,
			   access=AttrWriteType.READ,
			   unit="*C", format="4.3f",
			   doc="Temperature of the FPGA chip")
	def temperature(self):
		return self.RP.ams.temp

	@attribute(label="Ping check", dtype=str,
			   access=AttrWriteType.READ,
			   doc="Connection ping check")
	def ping(self):
		try:
			self.conn.ping()
		except Exception as e:	# should be PingError, but it's not working
			self.connection_error(e)
			if(self.reconnect_tries < self.reconnect):
				self.reconnect_tries += 1
				self.board_connect()	# try to reconnect if possible
			return "FAILED"
		else:
			self.reconnect_tries = 0	# reset reconnect counter
			return "OK"


if __name__ == "__main__":
	run((RedPitayaBoard,))